### ISSUE TITLE
Remove shelljs depencency

### ISSUE THREAD

**Issue by iapain** [fagbokforlaget/pdftohtmljs#12]

**Comment by rahilwazir** [comment]
Why removing shelljs dependency?

**Comment by iapain** [comment]
@rahilwazir as of nodejs 0.12 we now have `exec` and `execSync` so we don't really need shelljs

**Comment by rahilwazir** [comment]
@iapain Fair enough!

**Comment by iapain** [comment]
Fixed in v0.5.0
