### ISSUE TITLE
Cannot access pdftohtmlex debug data sent to stderr.

### ISSUE THREAD

**Issue by sundeepnarang** [fagbokforlaget/pdftohtmljs#13]
I needed all the data that pdftohtmlex child process outputs to stderr as it contains information like font info(when debug flag is 1) Also, if process fails I need this to figure out what went wrong

I did a temp resolution by just passing the 'error' variable to 'resolve' function for Promise.

Line 89 file lib/pdftohtml.js
resolve(); <--> resolve(error);

**Comment by iapain** [comment]
@sundeepnarang A pull request would be cool. Thanks :)

**Comment by iapain** [comment]
Fixed in #14
