### ISSUE TITLE
Sorry, this script requires pdf2htmlEX

### ISSUE THREAD

**Issue by hkaraoglu** [fagbokforlaget/pdftohtmljs#15]
`pdftohtmljs  sample.pdf`
I run this command on windows and it returns  me an error like below . How can I solve this? Please give a way which is in step by step.

> Sorry, this script requires pdf2htmlEX.
> Install it from http://github.com/coolwanglu/pdf2htmlEX
> Please install pdf2htmlEX

**Comment by iapain** [comment]
Please install [pdf2htmlEX](https://github.com/coolwanglu/pdf2htmlEX/wiki/Download) download guide. There is a pdf2htmlEX win32 static build. which you have to install and update `PATH` variable.
