### ISSUE TITLE
Need PDF to HTML with all images

### ISSUE THREAD

**Issue by cisaman** [fagbokforlaget/pdftohtmljs#16]
Hi Team

Your package is awesome. I need some help in that.
I have converted PDF to HTML from your package. But it will not return all images that we have in PDF separately, I want to know How can I have all images.

For e.g.,  I have a PDF with 3 images and I need html should have 3 images in that separately, so that I can reuse or replace those images in HTMl and later on I m converting that HTML to Image.

Please help.

Thank you in advance.

**Comment by iapain** [comment]
@cisaman Actually this is request for [coolwanglu/pdf2htmlEX](https://github.com/coolwanglu/pdf2htmlEX). It generates background images instead of separate images. Please create an issue there.
