### ISSUE TITLE
"Installing" pdf2htmlEX - Error: spawn pdf2htmlEX ENOENT or { code: 1 }

### ISSUE THREAD

**Issue by shahzoobgouhar** [fagbokforlaget/pdftohtmljs#20]
Hi,

I'm trying to build a file uploader, which should take in only pdf's and uses pdf2htmlEX / your wrapper to convert the files to html.

I ran `npm install pdftohtmljs` and I now see pdftohtmljs in my node_modules folder.

However, for the life of me I cannot even get your usage code to work :(

```
var pdftohtml = require('pdftohtmljs');
var converter = new pdftohtml("/uploads/test.pdf", "upload/test.html");

converter.convert('ipad').then(function() {
  console.log("Success");
}).catch(function(err) {
  console.error("Conversion error: " + err);
});

// If you would like to tap into progress then create
// progress handler
converter.progress(function(ret) {
  console.log ((ret.current*100.0)/ret.total + " %");
});

I get this error if I don't have pdf2html "installed"

events.js:183
throw er; // Unhandled 'error' event
^

Error: spawn pdf2htmlEX ENOENT
at _errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
at Function.Module.runMain (module.js:695:11)
at startup (bootstrap_node.js:188:16)
at bootstrap_node.js:609:3
```

And if I place pdf2thmlEX.exe in the root of my project I get this:

Sorry, this script requires pdf2htmlEX. Please make sure its already installed.
Install it from http://github.com/coolwanglu/pdf2htmlEX
{ code: 1 }

Also tried to make it available through PATH variable but no luck.
 
How do I "install" pdf2thmlEX correctly, what am I doing wrong?
@iapain and @jenack any help guys.

**Comment by DavinderSinghVH** [comment]
i have tried adding it to the path but its still not working can you please elaborate @iapain

**Comment by ket2310** [comment]
I need help with this as well.  The installation instructions are very vague, poorly written, and I don't speak Chinese.  WHERE do I put the exe file for pdf2htmlEX?

**Comment by DavinderSinghVH** [comment]
@ket2310 add folder path of pdf2htmlEX in your system variables inside path it will work

**Comment by ket2310** [comment]
I am working in node js.  Where does it need to go?  node_modules has pdftohtml and I believe that is where the exe is called.

**Comment by ket2310** [comment]
Details please?  Everything in this github repository is vague and ambiguous

**Comment by iapain** [comment]
I have added possibility to pass pdf2htmlEX path in env variable. If you are using it in code then set env variable like this before calling pdftohtmljs

`process.env.PDF2HTMLEX_BIN=c:\pdf2htmlex\pdf2htmlEX.exe`

Make sure you are using v0.5.4

**Comment by ket2310** [comment]
Thanks, Iapain.  I have gotten further along by doing some research.  Now I am getting and trying to resolve the Error: Can't open the manifest file.

**Comment by glucan1** [comment]
> Thanks, Iapain. I have gotten further along by doing some research. Now I am getting and trying to resolve the Error: Can't open the manifest file.

I have the same error, i even tried to run the converter from the pdf2htmlex folder but without any luck. If you find out, please write here some hints. Thanks
