### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by asifmai** [fagbokforlaget/pdftohtmljs#23]
Hello,
I am getting this error 
Please install pdf2htmlEX from https://github.com/coolwanglu/pdf2htmlEX
Conversion error: Error: spawn pdf2htmlEX ENOENT
How would I install it in windows and ubuntu?

**Comment by pires9** [comment]
http://soft.rubypdf.com/software/pdf2htmlex-windows-version
Download in this link the last version of pdf2htmlEX for windows
Unzip de package and add the folder unziped to system variables on windows.

For Ubuntu solution this link should work
http://opendesignarch.blogspot.com/2013/01/download-and-install-pdf2html.html

**Comment by iapain** [comment]
I'd recommend you to install it via docker https://hub.docker.com/r/bwits/pdf2htmlex
