### ISSUE TITLE
Limit memory/CPU usage on pdf2htmlEX process

### ISSUE THREAD

**Issue by pgcalixto** [fagbokforlaget/pdftohtmljs#27]
There seems to have a memory issue for some PDF files, as it can be seen in a issue in pdf2htmlEX: https://github.com/coolwanglu/pdf2htmlEX/issues/776.

This kind of file raises the following error:

```pdf
Lookup 'mark' Mark Positioning lookup 2 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'smcp' Lowercase to Small Capitals lookup 21 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Internal Error: Attempt to output 65744 into a 16-bit field. It will be truncated and the file may not be useful.
```

I have another file that displays the same error messages when trying to be converted: [66146383-Estudos Disciplinares XIV TI Trabalho Individual 2019.pdf](https://github.com/fagbokforlaget/pdftohtmljs/files/3602813/66146383-Estudos.Disciplinares.XIV.TI.Trabalho.Individual.2019.pdf).

The messages above can be searched for online. By searching them, it seems that there are some fonts that FontForge (a dependency of pdf2htmlEX) cannot convert (?).
When trying to convert files that have this problem, the process consumes all memory of the host computer.
Given this problem, there should be an option to limit pdf2htmlEX's spawned process, so that these files do not crash the system when trying to be coverted.

**Comment by iapain** [comment]
@pgcalixto This error comes from `pdf2htmlex` binary. Probably you should report it there.
