### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by haydenbleasel** [fagbokforlaget/pdftohtmljs#6]
When opening the HTML document:

```
Uncaught SyntaxError: Unexpected end of input

y @ DLdVetwT2o:267
L @ DLdVetwT2o:279
E @ DLdVetwT2o:280
(anonymous function) @ DLdVetwT2o:269
```

It appears to be referencing the `pdf2htmlEX.js`, so I'm debating whether it's an issue with that script or `pdftohtmljs`. Any ideas?

**Comment by iapain** [comment]
@haydenbleasel Looks like some problem with your pdf.

**Comment by haydenbleasel** [comment]
Hey sorry, this was caused by using `cheerio.load` with `decodeEntities: true`.
