### ISSUE TITLE
Re: Error code 

### ISSUE THREAD

**Issue by asimo** [fagbokforlaget/pdftohtmljs#9]
I am getting from cmd (w pdf in root):

pdftohtmljs test.pdf 

/usr/local/lib/node_modules/pdftohtmljs/lib/pdftohtml.js:97
          throw new Error("Error code: "+ code);
          ^

Error: Error code: 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/pdftohtmljs/lib/pdftohtml.js:97:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

All dependencies installed: using "engine": "node 5.11.1" to avoid the graceful-fs issue. 

 Any thoughts? 

Thanks

**Comment by asimo** [comment]
Works w smaller pdf made from Pages. I was trying to convert a large pdf- I'll move to comment section.

Thanks you

**Comment by asimo** [comment]
Thought I would add the failure was likely due to "Compress" pdf settings. Does work on large pdf very well. Thanks again.

**Comment by iapain** [comment]
@asimo you may wants to create this issue at coolwanglu/pdf2htmlEX
